---
title: "Learning Data Science With Data Justice"
description: |
  A short description of the post.
author:
  - name: Wylie Hampson
    url: {}
date: 2022-06-04
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


Since beginning my Masters degree at the Bren School of Environmental Science and Management at UC Santa Barbara I have made incredible progress to becoming an environmental data scientist. I am part of Bren’s inaugural Masters of Environmental Data Science Program where students are being taught how to work directly with data to help combat some of the major environmental problems that we as a species are facing. I have an undergraduate degree in biology from the University of Washington, but prior to coming to Bren, I had very little experience with data science before applying for the program. I thought that I had a pretty good idea about what I would be learning and what it would be like to actually be a data scientist professionally, but one area that my program has been heavily focused on that I didn’t expect as much before starting, was the environmental and social justice aspect, specifically data justice. My classmates and I have been learning about all of the important technical skills one might need to be a data scientist, but throughout my year here at Bren, the work has always been centered around thinking with a social and environmental justice mindset, which was something I wasn’t expecting. I’m not sure why I didn’t think my program would have much of a justice focus, but now that I’ve learned so much, it’s hard to imagine learning data science without thinking in a socially just way. During our final spring quarter at Bren we have been taking an Ethics and Bias in Environmental Data Science class that really centers in on how data can be used to both help and cause harm, some times without intention, and how it is important for new data scientists to be taught to have a conscious mind about these things. Our program has each of us working in groups on environmental data science capstone projects, and this class made me begin to relook at the project that I had been working on and how it may relate to environmental data justice. 
  So here’s a little background on what my capstone project revolves around. My capstone group and I have been working together with our faculty advisor Dr. Naomi Tague and her lab at Bren, the Tague Team Lab, to help them create a quicker and easier way for researchers to navigate through the datasets that are output by their ecohydrologic model called the Regional Hydro Ecological Simulation System, or RHESSys as it is referred to. Without getting too into the weeds of things, RHESSys is a model where researchers can take a specific study area, a forest or a watershed usually, and feed in some physical measurements such as temperature, precipitation, vegetation type, etc. and RHESSys will output a dataset with predicted measurements such as net primary productivity or evapotranspiration. This model is incredibly complex and uses all sorts of different equations to accurately predict these measurements, and it has been used in many different case studies to help answer real world questions. One thing about the RHESSys model is that it can produce datasets that can have upwards of 70 columns and millions of rows. As one can imagine that can be difficult to sift through and find meaningful relationships within, which is where my group came in. The goal of our project is to create a reproducible workflow that researchers can put their RHESSys output data into and the workflow will automatically help point them in the directions of variables and relationships that they might be interested in. When someone first hears about this project I think that it’s easy to initially think that it doesn’t really have anything to do with social justice in any way. But, as I’ve learned throughout my experience at Bren, no matter what, data can be a powerful tool that can affect people’s lives in ways that one might not even think of.
	So the purpose of our project isn’t directly focused on promoting environmental justice, but it also doesn’t seem to be causing any major harm, so why am I writing this blog post? Well, one major thing that I’ve learned so far at Bren is that data can be used for good, but it can also cause harm in ways that many people don’t think of, which is why it is important to write blog posts such as this to hopefully point out some of these issues to people. One critically important part of working with data is using full transparency and making sure that the data is accessible to all. So let’s take a look at my capstone project. Right away I think it’s pretty clear that this project is fairly complex and not easy to understand unless you’re trained in data science and machine learning and on top of that the RHESSys model is nearly impossible to use unless trained how to use it (I don’t even know how to run it!). That right away is an issue because it limits the vast majority of people from comprehending what is going on in these different forest and watershed systems. Knowing the interconnected relationships within an ecosystem can be important for more than just ecological reasons, it can allow policy makers to decide how to treat an area, it can help people learn more about the environments that they are living in, and it can help educate people about things like climate change and environmental degradation. By not making sure that everyone has equal access to information like this can keep people out of the conversation about how to protect our environment, and even people’s health and wellbeing. Watershed management is incredibly important when it comes to properly supplying people with ample amounts of fresh clean water. By not making this data as accessible as possible to all groups of people, it leaves marginalized communities vulnerable to being taken advantage of because if people don’t know what is going on in their watershed, the government doesn’t need to put as much effort into making sure it is properly managed.
	So now that we’ve learned about some of the issues behind keeping data from the public, how has our project helped contribute to making this data more accessible? Well, really the overarching goal of our project is doing just that! The scope of our project doesn’t involve making this data accessible to the average person, but that’s not an easy task, so we’re doing the first step in accomplishing that, which is first making it more accessible to a large group of researchers. Our project is hoping to both speed up the data interpretation for researchers, and hoping to bridge the gap between ecological scientists and data scientists. Many ecologists may not be trained to use machine learning or trained in data visualization, so our project is focusing on narrowing that gap. By doing this, the goal is that more insight will come from the RHESSys data at a faster pace, which will hopefully lead to new scientific discoveries, which will lead to a cleaner planet for all. Now it might be a little bit of a stretch to claim that our project is a direct cause of data justice, but I think that the reality of it is that data justice doesn’t just happen overnight. These things take time and they often have to be done in small incremental steps, and I really feel that by first making the data more accessible to more scientists and researchers, they can then work towards making the data, and the stories that the data has to tell, more accessible to all.
	Unfortunately, making the RHESSys data as accessible as possible isn’t within the scope of our capstone project because we simply don’t have enough time. So what would the next steps be to make RHESSys as social just as possible? Well as I stated above I think that the first thing is to make this data as accessible as possible. Make the app more available on the web and try to make it as fun and easy to use as possible. Make it something that people are curious about and want to look at. Make it as educational as possible, talk about the problems caused when watersheds aren’t properly cared for. Teach people what they can do to help, tell them how to reach out to government officials to try and make a difference. Really anything that would increase community interest and engagement is extremely important, but also making the data as accessible and easy to understand as possible. This would also involve using the RHESSys model in areas that are more vulnerable and that would have more of an effect on marginalized communities. Much like any kind of act that aims to improve the environment, it’s less about having your goal be to change the world all at once, and instead have small goals that help contribute to the overall goal of data justice. 
	It’s easy to get tunnel vision and only focus on one main goal when it comes to data science. Data science is used to discover new insights and optimize profits using new and exciting machine learning and data processing techniques. I think it can be easy to get so wrapped up in data science that it’s easy to not consider all of the different consequences and it can cause some serious harm. I really appreciate starting my data science career off at Bren because there has been a huge emphasis in our program focusing on environmental and social justice. If nothing else, it showed me the importance of being taught in this way. When I started my capstone project I didn’t think that it had very much to do with social justice and empowering people, but an important lesson that I learned is that any kind of data science project can have an effect on human rights and social justice, and that’s how the next generation of data scientists needs to be taught. There is a ton of power in data, and if not used properly, there can be major wrongs done. If new data scientists are trained to always ask themselves how a data project could have unintended effects on different communities, then data would be used much more often for good without the negative effects that we’ve seen examples of. It has been an amazing experience going through school and learning how I can use my new skills as a data scientist to improve the world and it is exciting to know that even if the job that I end up at doesn’t have social justice as its main objective, I know that I can still use my background to help contribute to solving some of these issues in ways that others may not think about. I think that with the proper training, data science will only improve and we will all work together to use data in the most positive ways possible. 
